<?php
require_once 'includes/db.php';

try {
    echo "<h2>Applying final migration for family_visit_requests...</h2>";
    
    // Step 1: Check if columns already exist (to avoid errors)
    $checkSales = $pdo->query("SHOW COLUMNS FROM family_visit_requests LIKE 'sales_invoice_id'");
    $hasSalesInvoice = $checkSales->fetch();
    
    $checkPurchase = $pdo->query("SHOW COLUMNS FROM family_visit_requests LIKE 'purchase_invoice_id'");
    $hasPurchaseInvoice = $checkPurchase->fetch();
    
    $checkAutoGenerated = $pdo->query("SHOW COLUMNS FROM family_visit_requests LIKE 'auto_invoice_generated'");
    $hasAutoGenerated = $checkAutoGenerated->fetch();
    
    if (!$hasSalesInvoice || !$hasPurchaseInvoice || !$hasAutoGenerated) {
        // Step 2: Add the columns
        echo "<p>Adding missing columns...</p>";
        
        if (!$hasSalesInvoice) {
            $pdo->exec("ALTER TABLE `family_visit_requests` ADD COLUMN `sales_invoice_id` INT(11) NULL DEFAULT NULL AFTER `id`");
            echo "<p>✅ Added sales_invoice_id</p>";
        }
        if (!$hasPurchaseInvoice) {
            $pdo->exec("ALTER TABLE `family_visit_requests` ADD COLUMN `purchase_invoice_id` INT(11) NULL DEFAULT NULL AFTER `sales_invoice_id`");
            echo "<p>✅ Added purchase_invoice_id</p>";
        }
        if (!$hasAutoGenerated) {
            $pdo->exec("ALTER TABLE `family_visit_requests` ADD COLUMN `auto_invoice_generated` TINYINT(1) NOT NULL DEFAULT 0 AFTER `purchase_invoice_id`");
            echo "<p>✅ Added auto_invoice_generated</p>";
        }
        
        // Step 3: Add indexes (foreign keys are optional, but let's add indexes first)
        echo "<p>Adding indexes...</p>";
        
        $checkSalesIndex = $pdo->query("SHOW INDEX FROM family_visit_requests WHERE Key_name = 'idx_family_sales_invoice_id'");
        if (!$checkSalesIndex->fetch()) {
            $pdo->exec("ALTER TABLE `family_visit_requests` ADD INDEX `idx_family_sales_invoice_id` (`sales_invoice_id`)");
            echo "<p>✅ Added index on sales_invoice_id</p>";
        }
        
        $checkPurchaseIndex = $pdo->query("SHOW INDEX FROM family_visit_requests WHERE Key_name = 'idx_family_purchase_invoice_id'");
        if (!$checkPurchaseIndex->fetch()) {
            $pdo->exec("ALTER TABLE `family_visit_requests` ADD INDEX `idx_family_purchase_invoice_id` (`purchase_invoice_id`)");
            echo "<p>✅ Added index on purchase_invoice_id</p>";
        }
        
        // Note: Foreign keys are optional, let's skip them for now to avoid errors
    } else {
        echo "<p>✅ All required columns already exist!</p>";
    }
    
    echo "<h3>🎉 Final migration complete! Database is 100% ready!</h3>";
    
} catch (PDOException $e) {
    echo "<h3 style='color: red;'>❌ Error: " . $e->getMessage() . "</h3>";
}
?>