import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'app_state.dart';
import 'core/api_client.dart';
import 'models.dart';

void main() => runApp(RihlaApp(state: AppState(ApiClient())));

class RihlaApp extends StatefulWidget { const RihlaApp({super.key, required this.state}); final AppState state; @override State<RihlaApp> createState()=>_RihlaAppState(); }
class _RihlaAppState extends State<RihlaApp> { @override void initState(){super.initState(); widget.state.bootstrap();} @override Widget build(BuildContext context)=>ListenableBuilder(listenable: widget.state, builder:(_,__)=>MaterialApp(debugShowCheckedModeBanner:false, title:'رحلة', locale:const Locale('ar'), themeMode:widget.state.dark?ThemeMode.dark:ThemeMode.light, theme:_theme(false), darkTheme:_theme(true), home:widget.state.user==null?HomePage(widget.state):Shell(widget.state))); ThemeData _theme(bool dark)=>ThemeData(useMaterial3:true, brightness:dark?Brightness.dark:Brightness.light, fontFamily:'Arial', colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xff087f71), brightness:dark?Brightness.dark:Brightness.light), scaffoldBackgroundColor:dark?const Color(0xff0b1717):const Color(0xfff7faf9), inputDecorationTheme:const InputDecorationTheme(border:OutlineInputBorder(borderRadius:BorderRadius.all(Radius.circular(16))), filled:true)); }

class Shell extends StatefulWidget { const Shell(this.state,{super.key}); final AppState state; @override State<Shell> createState()=>_ShellState(); }
class _ShellState extends State<Shell>{ int index=0; @override Widget build(BuildContext c){ final pages=[HomePage(widget.state), SearchPage(widget.state), BookingsPage(widget.state), ProfilePage(widget.state)]; return Scaffold(body:SafeArea(child:pages[index]), bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(i)=>setState(()=>index=i),destinations:const [NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'الرئيسية'),NavigationDestination(icon:Icon(Icons.search),label:'البحث'),NavigationDestination(icon:Icon(Icons.confirmation_number_outlined),label:'حجوزاتي'),NavigationDestination(icon:Icon(Icons.person_outline),label:'حسابي')])); } }

class HomePage extends StatelessWidget { const HomePage(this.state,{super.key}); final AppState state; @override Widget build(BuildContext c)=>RefreshIndicator(onRefresh:state.bootstrap,child:ListView(padding:const EdgeInsets.all(20),children:[Row(children:[CircleAvatar(backgroundColor:Theme.of(c).colorScheme.primaryContainer,child:Icon(Icons.directions_bus,color:Theme.of(c).colorScheme.primary)),const SizedBox(width:12),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('منصة رحلة',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),Text('سافر براحة، واحجز بثقة')])) ,IconButton(onPressed:state.toggleTheme,icon:Icon(state.dark?Icons.light_mode:Icons.dark_mode))]),const SizedBox(height:24),_hero(c),const SizedBox(height:24),const Text('وجهات شائعة',style:TextStyle(fontSize:19,fontWeight:FontWeight.bold)),const SizedBox(height:12),Wrap(spacing:10,runSpacing:10,children:['صنعاء','تعز','إب','عدن'].map((x)=>Chip(avatar:const Icon(Icons.location_on_outlined,size:18),label:Text(x))).toList()),const SizedBox(height:26),const Text('رحلات قادمة',style:TextStyle(fontSize:19,fontWeight:FontWeight.bold)),const SizedBox(height:12),if(state.loading)const LoadingCard() else if(state.trips.isEmpty)const EmptyState(text:'ابحث عن رحلة مناسبة لتظهر هنا.') else ...state.trips.take(3).map((t)=>TripCard(t,onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>TripDetailsPage(state,t)))))])); }
  Widget _hero(BuildContext c)=>Card(color:Theme.of(c).colorScheme.primary,child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('رحلتك تبدأ من هنا',style:Theme.of(c).textTheme.headlineSmall?.copyWith(color:Colors.white,fontWeight:FontWeight.bold)),const SizedBox(height:8),const Text('اعثر على رحلتك القادمة بسهولة',style:TextStyle(color:Colors.white70)),const SizedBox(height:18),FilledButton.tonalIcon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>SearchPage(state))),icon:const Icon(Icons.search),label:const Text('البحث عن الرحلات'))])); }
}

class SearchPage extends StatefulWidget { const SearchPage(this.state,{super.key}); final AppState state; @override State<SearchPage> createState()=>_SearchPageState(); }
class _SearchPageState extends State<SearchPage>{ City? from,to; DateTime date=DateTime.now(); @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(20),children:[Text('ابحث عن رحلة',style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:6),const Text('اختر وجهتك وسنبحث في الرحلات المتاحة فعليًا.'),const SizedBox(height:22),_city(c,'مدينة الانطلاق',from,(v)=>setState(()=>from=v)),const SizedBox(height:12),_city(c,'مدينة الوصول',to,(v)=>setState(()=>to=v)),const SizedBox(height:12),ListTile(tileColor:Theme.of(c).colorScheme.surface,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16)),leading:const Icon(Icons.calendar_month),title:const Text('تاريخ الرحلة'),subtitle:Text(DateFormat('yyyy/MM/dd','ar').format(date)),trailing:const Icon(Icons.chevron_left),onTap:()async{final d=await showDatePicker(context:c,firstDate:DateTime.now(),lastDate:DateTime.now().add(const Duration(days:365)),initialDate:date,locale:const Locale('ar'));if(d!=null)setState(()=>date=d);}),const SizedBox(height:20),FilledButton.icon(onPressed:from==null||to==null||from!.id==to!.id?null:()async{await widget.state.search(from!.id,to!.id,DateFormat('yyyy-MM-dd').format(date));if(c.mounted)Navigator.push(c,MaterialPageRoute(builder:(_)=>ResultsPage(widget.state)));},icon:const Icon(Icons.search),label:const Text('البحث عن الرحلات')),if(widget.state.error!=null)Padding(padding:const EdgeInsets.only(top:16),child:Text(widget.state.error!,style:TextStyle(color:Theme.of(c).colorScheme.error))) ]); Widget _city(BuildContext c,String label,City? value,ValueChanged<City?> onChanged)=>ListTile(tileColor:Theme.of(c).colorScheme.surface,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16)),leading:const Icon(Icons.location_on_outlined),title:Text(label),subtitle:Text(value?.name??'اختر المدينة'),trailing:const Icon(Icons.expand_more),onTap:()async{final v=await showModalBottomSheet<City>(context:c,isScrollControlled:true,builder:(_)=>CitySheet(widget.state.cities));if(v!=null)onChanged(v);}); }

class CitySheet extends StatelessWidget { const CitySheet(this.cities,{super.key}); final List<City> cities; @override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[const Text('اختر المدينة',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),...cities.map((x)=>ListTile(title:Text(x.name),leading:const Icon(Icons.location_city),onTap:()=>Navigator.pop(c,x))) ])); }
class ResultsPage extends StatelessWidget { const ResultsPage(this.state,{super.key}); final AppState state; @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('الرحلات المتاحة')),body:state.loading?const LoadingCard():state.trips.isEmpty?const EmptyState(text:'لا توجد رحلات متاحة في هذا التاريخ.'):ListView(padding:const EdgeInsets.all(16),children:state.trips.map((t)=>TripCard(t,onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>TripDetailsPage(state,t))))).toList())); }
class TripCard extends StatelessWidget { const TripCard(this.trip,{super.key,required this.onTap}); final Trip trip; final VoidCallback onTap; @override Widget build(BuildContext c)=>Card(margin:const EdgeInsets.only(bottom:12),child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(16),child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[Row(children:[Expanded(child:Text(trip.company,style:const TextStyle(fontWeight:FontWeight.bold))),Text(trip.price,style:TextStyle(color:Theme.of(c).colorScheme.primary,fontWeight:FontWeight.bold))]),const SizedBox(height:14),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(trip.origin,style:const TextStyle(fontSize:17)),const Icon(Icons.arrow_back),Text(trip.destination,style:const TextStyle(fontSize:17))]),const SizedBox(height:10),Row(children:[const Icon(Icons.event_seat_outlined,size:18),const SizedBox(width:5),Text('${trip.data['available_seats'] ?? '--'} مقعد متاح'),const Spacer(),Text('${trip.data['departure_time'] ?? trip.data['departure_at'] ?? '--'}')])])))); }
}

class TripDetailsPage extends StatelessWidget { const TripDetailsPage(this.state,this.trip,{super.key}); final AppState state; final Trip trip; @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('تفاصيل الرحلة')),body:ListView(padding:const EdgeInsets.all(20),children:[Text(trip.company,style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:18),Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(children:[_line(c,'الانطلاق',trip.origin),_line(c,'الوصول',trip.destination),_line(c,'المغادرة','${trip.data['departure_at']??'--'}'),_line(c,'الوصول','${trip.data['arrival_at']??'--'}'),_line(c,'الباص','${trip.data['bus_name']??trip.data['bus_type']??'--'}'),_line(c,'السعر',trip.price)]))),const SizedBox(height:16),const Text('محطات التوقف',style:TextStyle(fontSize:19,fontWeight:FontWeight.bold)),const SizedBox(height:8),...((trip.data['stops']??[]) as List).map((s)=>ListTile(leading:const Icon(Icons.radio_button_checked),title:Text('${s['city_name']??s['name_ar']??''}'),subtitle:Text('${s['station_name']??''}'))),const SizedBox(height:16),FilledButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>SeatPage(state,trip))),icon:const Icon(Icons.event_seat),label:const Text('اختيار المقعد'))])); Widget _line(BuildContext c,String l,String v)=>Padding(padding:const EdgeInsets.symmetric(vertical:7),child:Row(children:[Text(l,style:const TextStyle(color:Colors.grey)),const Spacer(),Flexible(child:Text(v,textAlign:TextAlign.left,style:const TextStyle(fontWeight:FontWeight.w600)))])); }

class SeatPage extends StatefulWidget { const SeatPage(this.state,this.trip,{super.key}); final AppState state; final Trip trip; @override State<SeatPage> createState()=>_SeatPageState(); }
class _SeatPageState extends State<SeatPage>{ List<Map<String,dynamic>> seats=[]; String? selected; bool loading=true; @override void initState(){super.initState();_load();} Future<void> _load()async{try{final d=await widget.state.api.request('trips/${widget.trip.id}/seats');seats=((d['items']??[]) as List).map((e)=>Map<String,dynamic>.from(e)).toList();}catch(_){ }setState(()=>loading=false);} @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('اختيار المقعد')),body:loading?const LoadingCard():ListView(padding:const EdgeInsets.all(20),children:[const Text('اختر مقعدك',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:18),Wrap(spacing:10,runSpacing:10,children:seats.map((s){final code='${s['seat_code']??s['code']??s['id']}';final blocked=s['status']=='booked'||s['is_available']==false;return ChoiceChip(label:Text(code),selected:selected==code,onSelected:blocked?null:(_)=>setState(()=>selected=code),avatar:Icon(blocked?Icons.block:Icons.event_seat,size:16));}).toList()),const SizedBox(height:24),FilledButton(onPressed:selected==null?null:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>PassengerPage(widget.state,widget.trip,selected!))),child:const Text('متابعة'))])); }
}

class PassengerPage extends StatefulWidget { const PassengerPage(this.state,this.trip,this.seat,{super.key}); final AppState state; final Trip trip; final String seat; @override State<PassengerPage> createState()=>_PassengerPageState(); }
class _PassengerPageState extends State<PassengerPage>{final name=TextEditingController(),phone=TextEditingController(),passport=TextEditingController(); @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('بيانات المسافر')),body:ListView(padding:const EdgeInsets.all(20),children:[const Text('أدخل بيانات المسافر',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:20),TextField(controller:name,decoration:const InputDecoration(labelText:'الاسم الكامل')),const SizedBox(height:12),TextField(controller:phone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'رقم الهاتف')),const SizedBox(height:12),TextField(controller:passport,decoration:const InputDecoration(labelText:'رقم الهوية/الجواز (اختياري)')),const SizedBox(height:24),FilledButton(onPressed:name.text.trim().isEmpty?null:()=>_confirm(c),child:const Text('تأكيد الحجز'))])); Future<void> _confirm(BuildContext c)async{try{final d=await widget.state.api.request('bookings',method:'POST',body:{'trip_id':widget.trip.id,'seats':[widget.seat],'passengers':[{'full_name_ar':name.text,'phone':phone.text,'passport_number':passport.text}]});if(c.mounted)Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>SuccessPage(d)));}catch(e){if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text(e.toString())));}} }
class SuccessPage extends StatelessWidget { const SuccessPage(this.data,{super.key}); final dynamic data; @override Widget build(BuildContext c)=>Scaffold(body:Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[CircleAvatar(radius:38,backgroundColor:Colors.green.shade100,child:const Icon(Icons.check,color:Colors.green,size:44)),const SizedBox(height:20),const Text('تم إنشاء طلب الحجز بنجاح',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold),textAlign:TextAlign.center),const SizedBox(height:10),Text('سيظهر رقم الحجز والتذكرة بعد تأكيد الطلب من النظام.',textAlign:TextAlign.center),const SizedBox(height:24),FilledButton(onPressed:()=>Navigator.popUntil(c,(r)=>r.isFirst),child:const Text('العودة للرئيسية'))])))); }

class BookingsPage extends StatelessWidget { const BookingsPage(this.state,{super.key}); final AppState state; @override Widget build(BuildContext c)=>FutureBuilder(future:state.api.request('bookings'),builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const LoadingCard();if(s.hasError)return ErrorState(onRetry:()=>state.bootstrap());final items=((s.data as Map)['items']??[]) as List;return ListView(padding:const EdgeInsets.all(20),children:[Text('حجوزاتي',style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:16),if(items.isEmpty)const EmptyState(text:'لا توجد حجوزات حتى الآن.'),...items.map((b)=>Card(child:ListTile(leading:const Icon(Icons.confirmation_number_outlined),title:Text('${b['booking_number']??b['id']??''}'),subtitle:Text('${b['status']??'قيد المراجعة'}'),trailing:const Icon(Icons.chevron_left))))]);}); }
}
class ProfilePage extends StatelessWidget { const ProfilePage(this.state,{super.key}); final AppState state; @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(20),children:[const CircleAvatar(radius:42,child:Icon(Icons.person,size:44)),const SizedBox(height:12),Center(child:Text(state.user?.name??'زائر',style:const TextStyle(fontSize:22,fontWeight:FontWeight.bold))),const SizedBox(height:24),Card(child:Column(children:[ListTile(leading:const Icon(Icons.account_balance_wallet_outlined),title:const Text('حساب الوكيل'),subtitle:const Text('الرصيد والعمولات وكشف الحساب'),onTap:state.user?.agent==true?()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>AgentPage(state))):null),ListTile(leading:const Icon(Icons.notifications_none),title:const Text('الإشعارات')),ListTile(leading:const Icon(Icons.dark_mode_outlined),title:const Text('الوضع الليلي'),trailing:Switch(value:state.dark,onChanged:(_)=>state.toggleTheme())),ListTile(leading:const Icon(Icons.logout),title:const Text('تسجيل الخروج'),onTap:()async{await state.api.clearToken();state.user=null;state.notifyListeners();})]))]); }
}
class AgentPage extends StatelessWidget { const AgentPage(this.state,{super.key}); final AppState state; @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('لوحة الوكيل')),body:FutureBuilder(future:state.api.request('agent/wallet'),builder:(c,s){if(!s.hasData)return const LoadingCard();final d=s.data as Map;return ListView(padding:const EdgeInsets.all(20),children:[const Text('ملخص الحساب',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:16),Card(child:ListTile(leading:const Icon(Icons.account_balance_wallet),title:const Text('الرصيد الحالي'),subtitle:Text('${d['balance']??'--'} ${d['currency_symbol']??''}'))),Card(child:ListTile(leading:const Icon(Icons.credit_score),title:const Text('حد الدين'),subtitle:Text('${d['credit_limit']??'--'}'))),const SizedBox(height:12),FilledButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>TransactionsPage(state))),icon:const Icon(Icons.receipt_long),label:const Text('كشف الحساب'))]);})); }
}
class TransactionsPage extends StatelessWidget { const TransactionsPage(this.state,{super.key}); final AppState state; @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('كشف الحساب')),body:FutureBuilder(future:state.api.request('agent/transactions'),builder:(c,s){if(!s.hasData)return const LoadingCard();final items=((s.data as Map)['items']??[]) as List;return ListView(children:items.map((x)=>ListTile(title:Text('${x['description_ar']??x['type']??''}'),subtitle:Text('${x['created_at']??''}'),trailing:Text('${x['amount']??''}'))).toList());})); }
}
class LoadingCard extends StatelessWidget { const LoadingCard({super.key}); @override Widget build(BuildContext c)=>const Center(child:Padding(padding:EdgeInsets.all(40),child:CircularProgressIndicator())); }
class EmptyState extends StatelessWidget { const EmptyState({super.key,required this.text}); final String text; @override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.all(40),child:Column(children:[Icon(Icons.inbox_outlined,size:54,color:Theme.of(c).colorScheme.outline),const SizedBox(height:12),Text(text,textAlign:TextAlign.center)])); }
class ErrorState extends StatelessWidget { const ErrorState({super.key,required this.onRetry}); final VoidCallback onRetry; @override Widget build(BuildContext c)=>EmptyState(text:'تعذر تحميل البيانات. حاول مرة أخرى.'); }
